service: portfolio-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  stackName: portfolio-site

  environment:
    TABLE_PREFIX: ${self:custom.tablePrefix}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:Scan"
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.tablePrefix}*"
      
package:
  individually: true

plugins:
  - serverless-s3-sync
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline # must appear last!

custom:
  tablePrefix: portfolio-${sls:stage}
  hostedZone: Z04395608SQRCH9GIVM9

  serverless-offline:
    httpPort: 8000

  s3Sync:
    - bucketNameKey: FrontendBucketKey
      localDir: ../frontend/build/

# https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.02.html
  dynamodb:
    stages:
      - dev
    start:
      port: 8001
      migrate: true
      seed: true
      inMemory: true
    seed:
      dev:
        sources:
          - table: ${self:custom.tablePrefix}-about
            sources: [./seed/about.json]
          - table: ${self:custom.tablePrefix}-projects
            sources: [./seed/projects.json]

functions:
  getBlob:
    handler: src/getBlob.handler
    events:
      - httpApi:
          path: /${sls:stage}/blob
          method: get

resources:
  Resources:
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        Tags:
          - Key: 'project'
            Value: portfolio-${sls:stage}

    originAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: OAI for accessing portfolio frontend bucket
    
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 's3:GetObject'
              Resource: !Join
                - ""
                - - !GetAtt FrontendBucket.Arn
                  - "/*"
              Principal:
                CanonicalUser: !GetAtt originAccessIdentity.S3CanonicalUserId
        Bucket: !Ref FrontendBucket

    # https://github.com/awslabs/aws-cloudformation-templates/blob/master/community/solutions/StaticS3CloudFront.yml
    Distribution:
        Type: AWS::CloudFront::Distribution
        DependsOn: originAccessIdentity
        Properties:
          DistributionConfig:
            Origins:
              - Id: frontend
                DomainName: !GetAtt FrontendBucket.RegionalDomainName
                S3OriginConfig:
                  OriginAccessIdentity: !Join 
                    - /
                    - - origin-access-identity
                      - cloudfront
                      - !Ref originAccessIdentity
              - Id: api
                DomainName: !Join
                  - ""
                  - - !Ref HttpApi
                    - .execute-api.${aws:region}.amazonaws.com
                CustomOriginConfig:
                  HTTPPort: 80
                  HTTPSPort: 443
                  OriginProtocolPolicy: https-only
                  OriginSSLProtocols:
                    - TLSv1.2
            Enabled: true
            HttpVersion: http2
            DefaultRootObject: index.html
            # Aliases:
            # - niccannon.com
            # - www.niccannon.com
            DefaultCacheBehavior:
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
              CachedMethods:
                - GET
                - HEAD
              Compress: true
              TargetOriginId: frontend
              ForwardedValues:
                QueryString: 'false'
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: redirect-to-https
              MinTTL: 0
              MaxTTL: 3600
              DefaultTTL: 3600
            CacheBehaviors:
              - PathPattern: "/${sls:stage}/*"
                TargetOriginId: api
                AllowedMethods:
                  - HEAD
                  - GET
                  - OPTIONS
                  - PUT
                  - PATCH
                  - DELETE
                  - POST
                CachedMethods:
                  - GET
                  - HEAD
                ForwardedValues:
                  QueryString: true
                  Cookies:
                    Forward: none
                MinTTL: 0
                MaxTTL: 0
                DefaultTTL: 0
                ViewerProtocolPolicy: redirect-to-https
            CustomErrorResponses:
              - ErrorCode: 404
                ResponseCode: 404
                ResponsePagePath: "/index.html"
              - ErrorCode: 403
                ResponseCode: 200
                ResponsePagePath: "/index.html"
            Restrictions:
              GeoRestriction:
                RestrictionType: none
            ViewerCertificate:
              # TODO: Setup with ACM cert
              CloudFrontDefaultCertificate: 'true'

    AboutTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tablePrefix}-about
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    ProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tablePrefix}-projects
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

  Outputs:
    DistributionUrl:
      Value: !GetAtt Distribution.DomainName

    FrontendBucketKey:
      Value: !Ref FrontendBucket
