name: Push
on:
  push:
    branches:
      - master

jobs:
  up:
    name: Pulumi Up (prod)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 # Sydney

      - name: Install Pulumi
        uses: pulumi/action-install-pulumi-cli@v1

      # build artefacts
      - run: npm run bootstrap
      - run: npm run build

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}